# Generated by Django 3.2.7 on 2021-10-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virada', '0007_auto_20211003_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
